# Generated by Django 4.2.5 on 2023-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='time_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
