# Generated by Django 4.2.5 on 2023-10-09 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_chatmessages_time_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 13, 29, 58, 62566)),
        ),
    ]
