# Generated by Django 4.2.5 on 2023-10-09 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatmessages_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 13, 30, 24, 520505)),
        ),
    ]
