# Generated by Django 4.2.5 on 2023-10-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_alter_chatmessages_time_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='seen',
        ),
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='time_now',
            field=models.DateTimeField(default='2023-10-12T16:41:28.300587'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
