# Generated by Django 4.2.5 on 2023-10-13 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_remove_chatmessages_seen_profile_online_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 11, 27, 43, 431531)),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 11, 27, 43, 433532)),
        ),
    ]
